### ISSUE TITLE
Incorrect country name morph in Russian

### ISSUE THREAD

**Issue by speller** [wapmorgan/Morphos#3]
When trying to get country names in Russian it have two issues:
1) It changes the character case to lowercase. Is is incorrect behaviour for abbreviation. Character case must be the same as in input string. We can't show names like `usa` or `uae` to customers, they must be in uppercase as in input string.
2) Abbreviation country names become incorrect in Dat case: `США` transforms to `сше`,  `ОАЭ` transforms to `оаи`. 
I think it is the common case of using this library to morph canonical country names in Russian and it is unusable now.

**Comment by speller** [comment]
Even the word `Россия` in the Dat case become `россие`... It is total fail...

**Comment by wapmorgan** [comment]
It's not intended to decline country names. It's only for personal human names.

**Comment by speller** [comment]
But your README says:

> // Following code will return original word if it's immutable:
> $form = $dec->getCase('поле', 'родительный'); // поля

Is the word `поле` a personal human name?

**Comment by wapmorgan** [comment]
It supports declination of two objects :

1. Personal names(Иванов Иван Иванович): FirstNamesDeclension, LastNamesDeclension and MiddleNamesDeclension.
2. Common nouns(поле, линейка, стол): GeneralDeclension. 

For now it does not have specific functionality to decline cities and countries.

**Comment by wapmorgan** [comment]
But thanks for note. I'll think about this functionality.

**Comment by speller** [comment]
It would be great addition to morph countries and cities. Hope it will be implemented.

**Comment by wapmorgan** [comment]
Added this functionality as **GeographicalNamesDeclension** class. You can update to **3.0.0** and test it.

**Comment by wapmorgan** [comment]
Is this issue still actually for you?

**Comment by speller** [comment]
Hi, I will check it during next week. Thank you for new functionality!

**Comment by wapmorgan** [comment]
What's about this problem? Did you try new functionality?

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 23.06 и не могу вам ответить.
По техническим вопросам пишите на vadim.k@realt.by, по организационным
на info@realt.by

S> What's about this problem? Did you try new functionality?
S> —
S> You are receiving this because you are subscribed to this thread.
S> Reply to this email directly, view it on GitHub, or mute the thread.
S>   
S>     
S> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wapmorgan/Morphos","title":"wapmorgan/Morphos","subtitle":"GitHub
S> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
S> in
S> GitHub","url":"https://github.com/wapmorgan/Morphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wapmorgan
S> in #3: What's about this problem? Did you try new
S> functionality?"}],"action":{"name":"View
S> Issue","url":"https://github.com/wapmorgan/Morphos/issues/3#issuecomment-310466842"}}}



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by

**Comment by speller** [comment]
It work good as I can see, thanks!
Single question: is it possible to process letter case correctly in abbreviations like USA, UAE and similar?

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 23.06 и не могу вам ответить.
По техническим вопросам пишите на vadim.k@realt.by, по организационным
на info@realt.by

AP> It work good as I can see, thanks!
AP> Single question: is it possible to process letter case correctly
AP> in abbreviations like USA, UAE and similar?
AP> —
AP> You are receiving this because you commented.
AP> Reply to this email directly, view it on GitHub, or mute the thread.
AP>   
AP>     
AP> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wapmorgan/Morphos","title":"wapmorgan/Morphos","subtitle":"GitHub
AP> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
AP> in
AP> GitHub","url":"https://github.com/wapmorgan/Morphos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@speller
AP> in #3: It work good as I can see, thanks!\r\nSingle question: is
AP> it possible to process letter case correctly in abbreviations like
AP> USA, UAE and similar?"}],"action":{"name":"View
AP> Issue","url":"https://github.com/wapmorgan/Morphos/issues/3#issuecomment-310623403"}}}



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by

**Comment by wapmorgan** [comment]
It's intended to decline russian names only, so why you using it with USA and others? Make a check like `preg_match('~^[а-я]$~ui', $name)` and only if it's true, decline with mophos.

**Comment by wapmorgan** [comment]
@speller have you tested this functionality?

**Comment by wapmorgan** [comment]
@speller Do you still affecting this issue?

**Comment by speller** [comment]
@wapmorgan Sorry for late reply. It seems everything fine now. Thanks a lot! My previous post was incorrect, sorry.

I have new question :) Is it possible to obtain correct proposal for city name for different cases? For example correct proposal for city `Новосибирск` is `в Новосибирск`, but for city `Владивосток` correct proposal is `во Владивосток`. With the library now I can create correct almost sentences such as `Посылка из Японии в Владивосток`. Fully correct one is `Посылка из Японии во Владивосток`. Another city names for proposal `во` are: `Владимир`, `Владикавказ`. It seems if city name or country name starts from `в` or `ф` and next letter is consonant we should use `во`. Could you implement this? 

Anyway, thank you for your job!

**Comment by wapmorgan** [comment]
@speller I have ... ок, давай тогда по русски.
Я вот думаю, может возвращать не просто 6 падежей, а добавить еще падежи типа GENITIVE_PREPOSITION и PREPOSITIONAL_PREPOSITION, в которых будут предлоги:
- `NOMINATIVE_PREPOSITION`: `во Владивосток`
- `GENITIVE_PROPOSAL`: `из Владивостока`
- `PREPOSITIONAL_PROPOSAL`: `о Владивостоке`
В общем, нужно время, чтобы подсобирать статистику предлогов и правила их использования.

**Comment by speller** [comment]
Может добавить параметр к методам getCase/getCases, чтобы к слову добавлялся предлог?

**Comment by wapmorgan** [comment]
Слишком большие изменения в сигнатуре из-за мелочи. Наверное такой вариант будет предпочтительным:
- добавить падеж `ACCUSATIVE_IN` в GeographicalNamesDeclension: название города в винительном + предлог в(во): `во Владивосток / в Самару`
- добавить падеж `PREPOSITIONAL_ABOUT` во все классы: слово в предложно + предлог о(об): `о Владивостоке / об образе / о доме`

**Comment by speller** [comment]
А можно сделать так, чтобы не менялся регистр символов, если передана аббревиатура на английском? Среди названий стран у меня может попадаться английское UAE. Я в шаблоне всё пропускаю через функцию склонения страны. По идее, логично не изменять ничего в таком случае, раз уж английское слово попадает в обработку русских слов.

**Comment by speller** [comment]
Про падежи и предлоги - можно и отдельными методами получать нужное. Мне кажется, это не принципиально. Главное - результат получить.
Еще раз спасибо за вашу работу!

**Comment by wapmorgan** [comment]
_По идее, логично не изменять ничего в таком случае, раз уж английское слово попадает в обработку русских слов._
Логично, но это как минимум проверка регулярным выражением перед каждым словом. Я подумаю, может приду к другому решению. Кстати, в каком фреймворке используете?
_Про падежи и предлоги - можно и отдельными методами получать нужное. Мне кажется, это не принципиально. Главное - результат получить._
Тоже думаю еще. Есть в планах сделать фабрику по типу `name($name)->case('Dative')->with()`, которая при касте в строку возвратит имя в дательном падеже с предлогом `с / со`. Но будет ли это удобно? И как тогда делать в плагинах к blade / twig ?
_Еще раз спасибо за вашу работу!_
Не за что. Рад, что моя работа будет приносить пользу. Российский язык нужно правильно обрабатывать, чтобы не потерять его красоту и не ломать жизнь перфекционистам и лингвистам.

**Comment by wapmorgan** [comment]
@speller I've added `RussianLanguage::in()` method to resolve this problem.
Usage:
```php
echo RussianLanguage::in(GeographicalNamesInflection::getCase('Владивосток', 'винительный')); => 'во Владивосток'
```

**Comment by speller** [comment]
Good news!
I'm waiting for the new version release

**Comment by wapmorgan** [comment]
Will be released today.
