### ISSUE TITLE
Не верное склонение Республика Крым

### ISSUE THREAD

**Issue by Edd-G** [wapmorgan/Morphos#31]
Родительный падеж: должно быть "Республики Крым".
Сейчас склоняет "Республики Крыма".
Остальные падежи не проверял, проверьте по возможности, Крым именно в такой связке не склоняется.

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 9 июля 2018 года и не могу вам сейчас ответить.
По техническим вопросам пишите на vadim.k@realt.by, по организационным
на info@realt.by

EG> Родительный падеж: должно быть "Республики Крым".
EG> Сейчас склоняет "Республики Крыма".
EG> —
EG> You are receiving this because you are subscribed to this thread.
EG> Reply to this email directly, view it on GitHub, or mute the thread.
EG> 
EG> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wapmorgan/Morphos","title":"wapmorgan/Morphos","subtitle":"GitHub
EG> repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open
EG> in
EG> GitHub","url":"https://github.com/wapmorgan/Morphos"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Не
EG> верное склонение Республика Крым (#31)"}],"action":{"name":"View
EG> Issue","url":"https://github.com/wapmorgan/Morphos/issues/31"}}} [
EG> { "@context": "http://schema.org", "@type": "EmailMessage",
EG> "potentialAction": { "@type": "ViewAction", "target":
EG> "https://github.com/wapmorgan/Morphos/issues/31", "url":
EG> "https://github.com/wapmorgan/Morphos/issues/31", "name": "View
EG> Issue" }, "description": "View this Issue on GitHub", "publisher":
EG> { "@type": "Organization", "name": "GitHub", "url":
EG> "https://github.com" } }, { "@type": "MessageCard", "@context":
EG> "http://schema.org/extensions", "hideOriginalBody": "false",
EG> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Не
EG> верное склонение Республика Крым (#31)", "sections": [ { "text":
EG> "", "activityTitle": "**Edd-G**", "activityImage":
EG> "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
EG> "activitySubtitle": "@Edd-G", "facts": [ { "name": "Repository: ",
EG> "value": "wapmorgan/Morphos" }, { "name": "Issue #: ", "value": 31
EG> } ] } ], "potentialAction": [ { "name": "Add a comment", "@type":
EG> "ActionCard", "inputs": [ { "isMultiLine": true, "@type":
EG> "TextInput", "id": "IssueComment", "isRequired": false } ],
EG> "actions": [ { "name": "Comment", "@type": "HttpPOST", "target":
EG> "https://api.github.com", "body": "{\n\"commandName\":
EG> \"IssueComment\",\n\"repositoryFullName\":
EG> \"wapmorgan/Morphos\",\n\"issueId\": 31,\n\"IssueComment\":
EG> \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue",
EG> "@type": "HttpPOST", "target": "https://api.github.com", "body":
EG> "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\":
EG> \"wapmorgan/Morphos\",\n\"issueId\": 31\n}" }, { "targets": [ {
EG> "os": "default", "uri":
EG> "https://github.com/wapmorgan/Morphos/issues/31" } ], "@type":
EG> "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe",
EG> "@type": "HttpPOST", "target": "https://api.github.com", "body":
EG> "{\n\"commandName\": \"MuteNotification\",\n\"threadId\":
EG> 351933200\n}" } ], "themeColor": "26292E" } ] 



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by

**Comment by Edd-G** [comment]
То же самое с Республикой Татарстан.

**Comment by wapmorgan** [comment]
Исправлено в **dev-master**: http://morphos.io/try/geography?input=%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B0+%D0%9A%D1%80%D1%8B%D0%BC
Спасибо за фидбек!
