### ISSUE TITLE
 Ханты-Мансийск

### ISSUE THREAD

**Issue by DeadAndFat** [wapmorgan/Morphos#53]
При склонении в предложный падеж получается "Хантах-Мансийске"

**Comment by wapmorgan** [comment]
Thanks, updated.

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 9 июля 2018 года и не могу вам сейчас ответить.
По техническим вопросам пишите на d.kusma@realt.by, по организационным
на info@realt.by

S> Closed #53.
S> —
S> You are receiving this because you are subscribed to this thread.
S> Reply to this email directly, view it on GitHub, or mute the thread.
S> [ { "@context": "http://schema.org", "@type": "EmailMessage",
S> "potentialAction": { "@type": "ViewAction", "target":
S> "https://github.com/wapmorgan/Morphos/issues/53?email_source=notifications\u0026email_token=AGCF7NQDFRT2T2MDLZTDLPLP6PXPNA5CNFSM4HMZDK7KYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSMMRRSY#event-2467895499",
S> "url":
S> "https://github.com/wapmorgan/Morphos/issues/53?email_source=notifications\u0026email_token=AGCF7NQDFRT2T2MDLZTDLPLP6PXPNA5CNFSM4HMZDK7KYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSMMRRSY#event-2467895499",
S> "name": "View Issue" }, "description": "View this Issue on GitHub",
S> "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by
