### ISSUE TITLE
Несколько ошибок

### ISSUE THREAD

**Issue by abordage** [wapmorgan/Morphos#54]
**Ошибки в склонении существительных:**

Библиотекарь
Делопроизводитель
Преподаватель
Представитель
Производитель
Слесарь
Строитель
Учитель
Крупье

**Ошибки в склонении геогр.названий:**

**Должны склоняться:**
[Барановичи](https://ru.wiktionary.org/wiki/%D0%91%D0%B0%D1%80%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87%D0%B8)
[Ивацевичи](https://ru.wiktionary.org/wiki/%D0%98%D0%B2%D0%B0%D1%86%D0%B5%D0%B2%D0%B8%D1%87%D0%B8)
[Ганцевичи](https://ru.wiktionary.org/wiki/%D0%93%D0%B0%D0%BD%D1%86%D0%B5%D0%B2%D0%B8%D1%87%D0%B8)
[Ляховичи](https://ru.wiktionary.org/wiki/%D0%9B%D1%8F%D1%85%D0%BE%D0%B2%D0%B8%D1%87%D0%B8)
[Смолевичи](https://ru.wiktionary.org/wiki/%D0%A1%D0%BC%D0%BE%D0%BB%D0%B5%D0%B2%D0%B8%D1%87%D0%B8)
[Ивацевичи](https://ru.wiktionary.org/wiki/%D0%98%D0%B2%D0%B0%D1%86%D0%B5%D0%B2%D0%B8%D1%87%D0%B8)
[Житковичи](https://ru.wiktionary.org/wiki/%D0%96%D0%B8%D1%82%D0%BA%D0%BE%D0%B2%D0%B8%D1%87%D0%B8)
[Калинковичи](https://ru.wiktionary.org/wiki/%D0%9A%D0%B0%D0%BB%D0%B8%D0%BD%D0%BA%D0%BE%D0%B2%D0%B8%D1%87%D0%B8)
[Климовичи](https://ru.wiktionary.org/wiki/%D0%9A%D0%BB%D0%B8%D0%BC%D0%BE%D0%B2%D0%B8%D1%87%D0%B8)
[Костюковичи](https://ru.wiktionary.org/wiki/%D0%9A%D0%BE%D1%81%D1%82%D1%8E%D0%BA%D0%BE%D0%B2%D0%B8%D1%87%D0%B8)
[Осиповичи](https://ru.wiktionary.org/wiki/%D0%9E%D1%81%D0%B8%D0%BF%D0%BE%D0%B2%D0%B8%D1%87%D0%B8)
Бешенковичи
Белыничи
Глубокое ([Герб Глубокого — изображение в серебряном поле](https://ru.wikipedia.org/wiki/%D0%93%D0%BB%D1%83%D0%B1%D0%BE%D0%BA%D0%BE%D0%B5_(%D0%B3%D0%BE%D1%80%D0%BE%D0%B4)))
Круглое ([по данным на 1 января 2016 года в Круглом](https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D1%83%D0%B3%D0%BB%D0%BE%D0%B5_(%D0%B3%D0%BE%D1%80%D0%BE%D0%B4)))

**Не должны склоняться:**
[Жодино](https://ru.wiktionary.org/wiki/%D0%96%D0%BE%D0%B4%D0%B8%D0%BD%D0%BE)
Березино ([Днем города в Березино считается день освобождения](https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D1%80%D0%B5%D0%B7%D0%B8%D0%BD%D0%BE_(%D0%B3%D0%BE%D1%80%D0%BE%D0%B4)))
Иваново
Вороново
[Дятлово](https://ru.wiktionary.org/wiki/%D0%94%D1%8F%D1%82%D0%BB%D0%BE%D0%B2%D0%BE)

**Все падежи с ошибкой:**
[Каменец](https://ru.wiktionary.org/wiki/%D0%9A%D0%B0%D0%BC%D0%B5%D0%BD%D0%B5%D1%86)
[Лунинец](https://ru.wiktionary.org/wiki/%D0%9B%D1%83%D0%BD%D0%B8%D0%BD%D0%B5%D1%86)
Городок(город) ([В Городке издаётся районная газета](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%BE%D0%BA_(%D0%B3%D0%BE%D1%80%D0%BE%D0%B4,_%D0%91%D0%B5%D0%BB%D0%BE%D1%80%D1%83%D1%81%D1%81%D0%B8%D1%8F)))
[Новогрудок](https://ru.wiktionary.org/wiki/%D0%9D%D0%BE%D0%B2%D0%BE%D0%B3%D1%80%D1%83%D0%B4%D0%BE%D0%BA)
Островец ([активное расширение жилого фонда Островца](https://ru.wikipedia.org/wiki/%D0%9E%D1%81%D1%82%D1%80%D0%BE%D0%B2%D0%B5%D1%86))

**Неправильный род.падеж:**
[Столбцы](https://ru.wiktionary.org/wiki/%D0%A1%D1%82%D0%BE%D0%BB%D0%B1%D1%86%D1%8B)
[Пружаны](https://ru.wiktionary.org/wiki/%D0%9F%D1%80%D1%83%D0%B6%D0%B0%D0%BD%D1%8B)
[Мосты](https://ru.wiktionary.org/wiki/%D0%9C%D0%BE%D1%81%D1%82%D1%8B)
[Ошмяны](https://ru.wiktionary.org/wiki/%D0%9E%D1%88%D0%BC%D1%8F%D0%BD%D1%8B)
[Горки](https://ru.wiktionary.org/wiki/%D0%93%D0%BE%D1%80%D0%BA%D0%B8)
[Чаусы](https://ru.wiktionary.org/wiki/%D0%A7%D0%B0%D1%83%D1%81%D1%8B)
Марьина Горка
Червень ([На 1989 год в составе г. Червеня](https://ru.wikipedia.org/wiki/%D0%A7%D0%B5%D1%80%D0%B2%D0%B5%D0%BD%D1%8C))
Орша - орф.ошибка(Оршы)

**Разное:**
Старые Дороги ([В 1871 году помещик Гогенлоэ в Старых Дорогах основал смолокурню](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%B0%D1%80%D1%8B%D0%B5_%D0%94%D0%BE%D1%80%D0%BE%D0%B3%D0%B8))
Ушачи ([Гетто в Ушачах](https://ru.wikipedia.org/wiki/%D0%A3%D1%88%D0%B0%D1%87%D0%B8))
Буда-Кошелево(Первая часть не должна склоняться)

**Comment by wapmorgan** [comment]
Спасибо.
Не согласен в:
1. *Не должны склоняться:* - Согласно той же википедии, названия на -ино [должны склоняться](https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%BB%D0%BE%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B3%D0%B5%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85_%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B9_%D0%B2_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC_%D1%8F%D0%B7%D1%8B%D0%BA%D0%B5#%D0%A1%D0%BB%D0%B0%D0%B2%D1%8F%D0%BD%D1%81%D0%BA%D0%B8%D0%B5_%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F,_%D0%BE%D0%BA%D0%B0%D0%BD%D1%87%D0%B8%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B5%D1%81%D1%8F_%D0%BD%D0%B0_-%D0%BE%D0%B2(%D0%BE),_-%D1%91%D0%B2(%D0%BE),_-%D0%B5%D0%B2(%D0%BE),_-%D0%B8%D0%BD(%D0%BE),_-%D1%8B%D0%BD(%D0%BE)).
2. Столбцы, Пружаны, Мосты, Ошмяны - не получается выделить особенности, на основе которых можно было бы однозначно верно определить окончание.
Остальное исправлено.

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 9 июля 2018 года и не могу вам сейчас ответить.
По техническим вопросам пишите на d.kusma@realt.by, по организационным
на info@realt.by

S> Спасибо.
S> Не согласен в:
S> Не должны склоняться:- Согласно той же википедии, названия на -ино
S> должны склоняться.Столбцы, Пружаны, Мосты, Ошмяны - не получается
S> выделить особенности, на основе которых можно было бы однозначно верно определить окончание.
S> Остальное исправлено.
S> —
S> You are receiving this because you are subscribed to this thread.
S> Reply to this email directly, view it on GitHub, or mute the thread.
S> [  {  "@context": "http://schema.org",  "@type": "EmailMessage", 
S> "potentialAction": {  "@type": "ViewAction",  "target":
S> "https://github.com/wapmorgan/Morphos/issues/54?email_source=notifications\u0026email_token=AGCF7NRYNNRWGQC2GCTYRMTP6PXNZA5CNFSM4HP5FKEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZO3NZI#issuecomment-509458149",
S> "url":
S> "https://github.com/wapmorgan/Morphos/issues/54?email_source=notifications\u0026email_token=AGCF7NRYNNRWGQC2GCTYRMTP6PXNZA5CNFSM4HP5FKEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZO3NZI#issuecomment-509458149",
S> "name": "View Issue"  },  "description": "View this Issue on
S> GitHub",  "publisher": {  "@type": "Organization",  "name":
S> "GitHub",  "url": "https://github.com"  }  }  ] 



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by

**Comment by wapmorgan** [comment]
Изменения вошли в релиз 3.2.18.
