### ISSUE TITLE
Египет

### ISSUE THREAD

**Issue by loskov** [wapmorgan/Morphos#56]
```
var_dump(
    morphos\Russian\GeographicalNamesInflection::getCases('Египет')
);
```
```
array(6) {
  ["nominative"]=>
  string(12) "Египет"
  ["genitive"]=>
  string(14) "Египета"
  ["dative"]=>
  string(14) "Египету"
  ["accusative"]=>
  string(12) "Египет"
  ["ablative"]=>
  string(16) "Египетом"
  ["prepositional"]=>
  string(14) "Египете"
}
```

**Comment by wapmorgan** [comment]
Thanks, updated.

**Comment by martynenko-dmitry** [comment]
Здравствуйте .

Я нахожусь в отпуске до 9 июля 2018 года и не могу вам сейчас ответить.
По техническим вопросам пишите на d.kusma@realt.by, по организационным
на info@realt.by

S> Thanks, updated.
S> —
S> You are receiving this because you are subscribed to this thread.
S> Reply to this email directly, view it on GitHub, or mute the thread.
S> [ { "@context": "http://schema.org", "@type": "EmailMessage",
S> "potentialAction": { "@type": "ViewAction", "target":
S> "https://github.com/wapmorgan/Morphos/issues/56?email_source=notifications\u0026email_token=AGCF7NSDBEIHMA26UDDJFZTP6PXMPA5CNFSM4HZBXM42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZO3NFY#issuecomment-509458071",
S> "url":
S> "https://github.com/wapmorgan/Morphos/issues/56?email_source=notifications\u0026email_token=AGCF7NSDBEIHMA26UDDJFZTP6PXMPA5CNFSM4HZBXM42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZO3NFY#issuecomment-509458071",
S> "name": "View Issue" }, "description": "View this Issue on GitHub",
S> "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]



-- 
C наилучшими пожеланиями,
Интернет центр "Realt.by - Недвижимость"
Дмитрий Мартыненко

тел:      +375 29 679-77-75
mailto: dima@realt.by
skype: dmitry-martynenko
www: http://realt.by
